version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=your_database
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
    ports:
      - "5432:5432"
  app:
    build: ./
    container_name: "web3"
    ports:
      - "8080:8080"
